# Solver SCIP
SOLVER_MODE_RELAX = "relax"
SOLVER_MODE_MILP = "milp"

VAR_TYPE_BINARY = "BINARY"
VAR_TYPE_INTEGER = "INTEGER"
VAR_TYPE_CONTINUOUS = "CONTINUOUS"

SCIP_STATUS_OPTIMAL = "optimal"
SCIP_STATUS_INFEASIBLE = "infeasible"
SCIP_STATUS_GAPLIMIT = "gaplimit"
SCIP_STATUS_USERINTERRUPT = "userinterrupt"
SCIP_STATUS_TIMELIMIT = "timelimit"

PROCESS_INTERRUPT_MSG = "Process is interrupted ..."
