# Solver SCIP
SOLVER_MODE_RELAX = "relax"
SOLVER_MODE_MILP = "milp"

VAR_TYPE_BINARY = "BINARY"
VAR_TYPE_INTEGER = "INTEGER"
VAR_TYPE_CONTINUOUS = "CONTINUOUS"

SCIP_STATUS_OPTIMAL = "optimal"
SCIP_STATUS_INFEASIBLE = "infeasible"
SCIP_STATUS_GAPLIMIT = "gaplimit"
SCIP_STATUS_USERINTERRUPT = "userinterrupt"
SCIP_STATUS_TIMELIMIT = "timelimit"

PRESOLVING_DEFAULT = "default"
PRESOLVING_AGGRESSIVE = "aggressive"
PRESOLVING_FAST = "fast"

EMPHASIS_EASYCIP = "easycip"
EMPHASIS_FEASIBILITY = "feasibility"
EMPHASIS_OPTIMALITY = "optimality"
EMPHASIS_HARDLP = "hardlp"

PROCESS_INTERRUPT_MSG = "Process is interrupted ..."
