# Solver SCIP
SOLVER_MODE_RELAX = "relax"
SOLVER_MODE_MILP = "milp"

VAR_TYPE_BINARY = "BINARY"
VAR_TYPE_INTEGER = "INTEGER"
VAR_TYPE_CONTINUOUS = "CONTINUOUS"

SCIP_STATUS_OPTIMAL = "optimal"
SCIP_STATUS_INFEASIBLE = "infeasible"
SCIP_STATUS_GAPLIMIT = "gaplimit"
SCIP_STATUS_USERINTERRUPT = "userinterrupt"
SCIP_STATUS_TIMELIMIT = "timelimit"

SCIP_PARAM_CONFLICT_PREFERBINARY = "conflict/preferbinary"
SCIP_PARAM_BRANCHING_PREFERBINARY = "branching/preferbinary"
SCIP_PARAM_HEURISTICS_FARKASDIVING_FREQ = "heuristics/farkasdiving/freq"
SCIP_PARAM_HEURISTICS_FEASPUMP_FREQ = "heuristics/feaspump/freq"
SCIP_PARAM_HEURISTICS_RANDROUNDING_FREQ = "heuristics/randrounding/freq"
SCIP_PARAM_HEURISTICS_SHIFTANDPROPAGATE_FREQ = "heuristics/shiftandpropagate/freq"
SCIP_PARAM_HEURISTICS_SHIFTING_FREQ = "heuristics/shifting/freq"
SCIP_PARAM_LP_INITALGORITHM = "lp/initalgorithm"
SCIP_PARAM_LIMITS_GAP = "limits/gap"
SCIP_PARAM_LIMITS_TIME = "limits/time"
SCIP_PARAM_RANDOMIZATION_LPSEED = "randomization/lpseed"

PRESOLVING_DEFAULT_KEY = "default"
PRESOLVING_AGGRESSIVE_KEY = "aggressive"
PRESOLVING_FAST_KEY = "fast"
EMPHASIS_EASYCIP_KEY = "easycip"
EMPHASIS_FEASIBILITY_KEY = "feasibility"
EMPHASIS_OPTIMALITY_KEY = "optimality"
EMPHASIS_HARDLP_KEY = "hardlp"
NUMERICS_INSTABILITY_KEY = "numerics_instability"
CONFLICT_PREFERBINARY_KEY = SCIP_PARAM_CONFLICT_PREFERBINARY.replace("/", "_")
BRANCHING_PREFERBINARY_KEY = SCIP_PARAM_BRANCHING_PREFERBINARY.replace("/", "_")
HEURISTICS_FARKASDIVING_FREQ_KEY = SCIP_PARAM_HEURISTICS_FARKASDIVING_FREQ.replace("/", "_")
HEURISTICS_FEASPUMP_FREQ_KEY = SCIP_PARAM_HEURISTICS_FEASPUMP_FREQ.replace("/", "_")
HEURISTICS_RANDROUNDING_FREQ_KEY = SCIP_PARAM_HEURISTICS_RANDROUNDING_FREQ.replace("/", "_")
HEURISTICS_SHIFTANDPROPAGATE_FREQ_KEY = SCIP_PARAM_HEURISTICS_SHIFTANDPROPAGATE_FREQ.replace("/", "_")
HEURISTICS_SHIFTING_FREQ_KEY = SCIP_PARAM_HEURISTICS_SHIFTING_FREQ.replace("/", "_")
LP_INITALGORITHM_KEY = SCIP_PARAM_LP_INITALGORITHM.replace("/", "_")

PROCESS_INTERRUPT_MSG = "Process is interrupted ..."
